---
- hosts: all
  become: true
  vars:
    user_name: felix
    zsh_custom: /home/{{ user_name }}/.oh-my-zsh/custom
    extensions:
      - pkief.material-icon-theme
      - eamodio.gitlens
      - dbaeumer.vscode-eslint
  roles:
    - role: base
    - role: work
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ user_name }}"
          oh_my_zsh:
            theme: spaceship
            plugins:
              - git
              - zsh-syntax-highlighting
              - zsh-autosuggestions
