---
- name: Setup workstation
  hosts: all
  become: true
  remote_user: felix
  vars:
    user_name: felix
    zsh_custom: /home/{{ user_name }}/.oh-my-zsh/custom
    extensions:
      - pkief.material-icon-theme
      - eamodio.gitlens
      - dbaeumer.vscode-eslint
  tasks:
    - name: change user shell to zsh 
      become: yes
      ansible.builtin.user:
        name: "felix"
        shell: /bin/zsh
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ user_name }}"
          oh_my_zsh:
            theme: spaceship
            plugins:
              - git
              - zsh-syntax-highlighting
              - zsh-autosuggestions
    - role: base
    - role: work

