---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name: 
        - htop
        - tmux
        - curl
        - git
        - zsh

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: Set wallpaper
    command: >
      gsettings set org.gnome.desktop.background picture-uri "file:///usr/share/backgrounds/ansible-wallpaper.png"
    become_user: felix
  
  - name: set wallpaper position
    become_user: felix
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: Download and install Oh My Zsh
    shell: >
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    args:
      executable: /bin/bash
    become_user: felix

  - name: Set zsh as default shell for user
    user:
      name: felix
      shell: /bin/zsh
  - 