---
- hosts: localhost
  connection: local
  become: true

vars:
  - user_name: felix

tasks:
  - name: Install dependencies for Oh My Zsh
    apt:
      name:
        - curl
        - git
      state: present

  - name: Install Oh My Zsh
    shell: |
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    args:
      executable: /bin/bash
    become_user: "{{ user_name }}"

  - name: Set Zsh as default shell for user
    user:
      name: "{{ user_name }}"
      shell: /bin/zsh