- name: Configure localhost
  hosts: localhost
  connection: local
  become: true

  vars:
    user_name: felix
    wallpaper_path: /usr/share/backgrounds/wallpaper.png
    extensions:
      - vscodium.vscodium
      - zhuangtongfa.material-theme
      - eamodio.gitlens
      - dsznajder.es7-react-js-snippets

  tasks:
    - name: Install Oh My Zsh!
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" ""
      become_user: "{{ user_name }}"

    - name: Clone spaceship-prompt theme repository
      git:
        repo: "https://github.com/denysdovhan/spaceship-prompt.git"
        dest: "/home/{{ user_name }}/.oh-my-zsh/custom/themes/spaceship-prompt"
        clone: yes
        force: yes
      become_user: "{{ user_name }}"

    - name: Set spaceship-prompt theme as default
      lineinfile:
        path: "/home/{{ user_name }}/.zshrc"
        regexp: "^ZSH_THEME=.*"
        line: "ZSH_THEME=\"spaceship-prompt/spaceship\""
        backup: yes
      become_user: "{{ user_name }}"

    - name: Set wallpaper
      command: >
        gsettings set org.gnome.desktop.background picture-uri "file://{{ wallpaper_path }}"
      become_user: "{{ user_name }}"

    - name: Install VSCodium and extensions
      apt_repository:
        repo: deb [trusted=yes] https://apt.vscodium.com/ stable main
        update_cache: yes
      apt:
        name:
          - codium
          - fonts-firacode
        state: present

    - name: Install VSCodium extensions
      command: >
        codium --install-extension {{ item }}
      become_user: "{{ user_name }}"
      loop: "{{ extensions }}"
