- ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
    - ansible.builtin.include_tasks: packages/ohmyzsh.yml
    - ansible.builtin.include_tasks: packages/asdf.yml
    - ansible.builtin.include_tasks: software/codium.yml
    - ansible.builtin.include_tasks: desktop/appearence.yml