- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
    - include_tasks: packages/ohmyzsh.yml
    - include_tasks: software/codium.yml
    - include_tasks: desktop/appearence.yml