- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  changed_when: false
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - curl
      - git
      - libx11-xcb-dev
      - libasound2
      - libatk1.0-0
      - libcairo2
      - libcups2
      - libexpat1
      - libfontconfig1
      - libfreetype6
      - libgcc-s1
      - libglib2.0-0
      - libgtk-3-0
      - libnspr4
      - libnss3
      - libpango-1.0-0
      - libx11-xcb1
      - libxcb-dri3-0
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxi6
      - libxrandr2
      - libxrender1
      - libxtst6
      - wget
      - zsh
      - python3-pip
      - python3-psutil
      - python3-dbus
    state: present

- name: change user shell to zsh 
  become: true
  user:
    name: felix
    shell: /bin/zsh

